# Generated by Django 3.2.13 on 2023-01-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pict',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
