# Generated by Django 3.2.13 on 2023-01-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ss3gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNo', models.CharField(max_length=200)),
                ('NAME', models.CharField(max_length=200)),
                ('ENGLISH', models.FloatField(null=True)),
                ('MATHEMATICS', models.FloatField(null=True)),
                ('PHYSICS', models.FloatField(null=True)),
                ('CHEMISTRY', models.FloatField(null=True)),
                ('BIOLOGY', models.FloatField(null=True)),
                ('ANIMALHUSBANDRY', models.FloatField(null=True)),
                ('CIVICEDUCATION', models.FloatField(null=True)),
                ('ISLAMICSTUDIES', models.FloatField(null=True)),
                ('HAUSALANGUAGE', models.FloatField(null=True)),
                ('TOTAL', models.FloatField(null=True)),
                ('AVERAGE', models.FloatField(null=True)),
                ('POSITION', models.FloatField(null=True)),
                ('GENDER', models.CharField(max_length=20)),
                ('OUTOF', models.FloatField(null=True)),
                ('CLASS', models.FloatField(null=True)),
                ('TERM', models.CharField(max_length=20)),
                ('YEAR', models.IntegerField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
