# Generated by Django 3.2.13 on 2023-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_ss3gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ss3gold',
            name='CLASS',
            field=models.CharField(max_length=200),
        ),
    ]
