# Generated by Django 3.2.13 on 2023-01-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ss3gold_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ss3gold',
            name='ANIMALHUSBANDRY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='BIOLOGY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='CHEMISTRY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='CIVICEDUCATION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='ENGLISH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='HAUSALANGUAGE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='ISLAMICSTUDIES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='MATHEMATICS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='PHYSICS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='POSITION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ss3gold',
            name='TOTAL',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
