# Generated by Django 3.2.13 on 2023-01-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230128_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ss3gold',
            new_name='Science',
        ),
    ]
