# Generated by Django 3.2.13 on 2023-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_ss3gold_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='OUTOF',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='TERM',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
