# Generated by Django 3.2.13 on 2023-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230202_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pict',
            field=models.ImageField(blank=True, default='avatar.jpeg', null=True, upload_to=''),
        ),
    ]
