# Generated by Django 3.2.13 on 2023-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_teacher_pict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pict',
            new_name='fpict',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='spict',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
