# Generated by Django 3.2.13 on 2023-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230217_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='GENDER',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='science',
            name='YEAR',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20),
        ),
    ]
