# Generated by Django 3.2.13 on 2023-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230218_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='GENDER',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='arts',
            name='TERM',
            field=models.CharField(choices=[('First', 'FIRST'), ('Second', 'SECOND'), ('Third', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='YEAR',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20),
        ),
        migrations.AlterField(
            model_name='junior',
            name='GENDER',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='junior',
            name='TERM',
            field=models.CharField(choices=[('First', 'FIRST'), ('Second', 'SECOND'), ('Third', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='junior',
            name='YEAR',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20),
        ),
        migrations.AlterField(
            model_name='science',
            name='TERM',
            field=models.CharField(choices=[('First', 'FIRST'), ('Second', 'SECOND'), ('Third', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sone',
            name='GENDER',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sone',
            name='TERM',
            field=models.CharField(choices=[('First', 'FIRST'), ('Second', 'SECOND'), ('Third', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sone',
            name='YEAR',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20),
        ),
    ]
