# Generated by Django 3.2.13 on 2023-03-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='GENDER',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='arts',
            name='TERM',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='junior',
            name='GENDER',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='junior',
            name='TERM',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='GENDER',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='science',
            name='TERM',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sone',
            name='GENDER',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sone',
            name='TERM',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD')], max_length=20, null=True),
        ),
    ]
