# Generated by Django 3.2.13 on 2023-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20230311_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='sone',
            name='CIVICEDUCATION',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='fpict',
            field=models.ImageField(blank=True, default='DSC_1969.jpg', null=True, upload_to=''),
        ),
    ]
