# Generated by Django 3.2.13 on 2023-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20230404_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='junior',
            old_name='AGRICULTURALSCIENCE',
            new_name='BASICSCIENCEANDTECHNOLOGY',
        ),
        migrations.RenameField(
            model_name='junior',
            old_name='BASICSCIENCE',
            new_name='CULTURALANDCREATIVEARTS',
        ),
        migrations.RenameField(
            model_name='junior',
            old_name='BASICTECHNOLOGY',
            new_name='ENGLISHSTUDIES',
        ),
        migrations.RenameField(
            model_name='junior',
            old_name='CCA',
            new_name='HISTORY',
        ),
        migrations.RenameField(
            model_name='junior',
            old_name='CIVICEDUCATION',
            new_name='ISLAMICRELIGIOUSSTUDIES',
        ),
        migrations.RenameField(
            model_name='junior',
            old_name='ENGLISH',
            new_name='NATIONALVALUES',
        ),
        migrations.RenameField(
            model_name='junior',
            old_name='ISLAMICSTUDIES',
            new_name='PREVOCATIONALSTUDIES',
        ),
        migrations.RemoveField(
            model_name='junior',
            name='LITERATURE',
        ),
        migrations.RemoveField(
            model_name='junior',
            name='PHE',
        ),
        migrations.RemoveField(
            model_name='junior',
            name='SOCIALSTUDIES',
        ),
        migrations.AddField(
            model_name='arts',
            name='LITERATURE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
